### ISSUE TITLE
Error with AngularFire2

### ISSUE THREAD

**Issue by matthewmilligan** [NewtonJoshua/MovieSeatReservation#1]
I have tried to run this app with **ng serve** but my Terminal gives me a large list errors.

ERROR in /Users/Milligan/Documents/Angular/MovieSeatReservation/node_modules/angularfire2/database/firebase_object_observable.d.ts (11,31): Namespace 'firebase' has no exported member 'Promise'.
ERROR in /Users/Milligan/node_modules/angularfire2/firebase.app.module.d.ts (1,32): Cannot find module '@angular/core'.
ERROR in /Users/Milligan/Documents/Angular/MovieSeatReservation/node_modules/angularfire2/auth/auth.d.ts (4,29): Cannot find module '../app/index'.
ERROR in /Users/Milligan/Documents/Angular/MovieSeatReservation/node_modules/angularfire2/auth/auth.module.d.ts (2,29): Cannot find module '../app/index'.
ERROR in /Users/Milligan/Documents/Angular/MovieSeatReservation/node_modules/angularfire2/angularfire2.ts (6,15): Cannot find module './angularfire2/angularfire2'.
ERROR in /Users/Milligan/Documents/Angular/MovieSeatReservation/node_modules/angularfire2/database/firebase_list_observable.d.ts (7,81): Cannot find module '../interfaces'.
ERROR in /Users/Milligan/Documents/Angular/MovieSeatReservation/node_modules/angularfire2/database/firebase_list_observable.d.ts (14,62): Namespace 'firebase' has no exported member 'Promise'.
ERROR in /Users/Milligan/Documents/Angular/MovieSeatReservation/node_modules/angularfire2/database/firebase_list_observable.d.ts (15,48): Namespace 'firebase' has no exported member 'Promise'.
ERROR in /Users/Milligan/Documents/Angular/MovieSeatReservation/node_modules/angularfire2/database/firebase_list_observable.d.ts (16,92): Namespace 'firebase' has no exported member 'Promise'.
ERROR in /Users/Milligan/node_modules/angularfire2/angularfire2.d.ts (2,32): Cannot find module '@angular/core'.
ERROR in /Users/Milligan/Documents/Angular/MovieSeatReservation/node_modules/angularfire2/database/firebase_object_observable.d.ts (12,37): Namespace 'firebase' has no exported member 'Promise'.
ERROR in /Users/Milligan/Documents/Angular/MovieSeatReservation/node_modules/angularfire2/database/firebase_object_observable.d.ts (13,24): Namespace 'firebase' has no exported member 'Promise'.
ERROR in /Users/Milligan/Documents/Angular/MovieSeatReservation/node_modules/angularfire2/database/database.d.ts (2,10): Module '"/Users/Milligan/Documents/Angular/MovieSeatReservation/node_modules/angularfire2/angularfire2"' has no exported member 'FirebaseApp'.
ERROR in /Users/Milligan/Documents/Angular/MovieSeatReservation/node_modules/angularfire2/database/database.d.ts (4,83): Cannot find module '../interfaces'.
ERROR in /Users/Milligan/Documents/Angular/MovieSeatReservation/node_modules/angularfire2/database/firebase_list_factory.d.ts (3,56): Cannot find module '../interfaces'.
ERROR in /Users/Milligan/Documents/Angular/MovieSeatReservation/node_modules/angularfire2/database/firebase_object_factory.d.ts (3,58): Cannot find module '../interfaces'.
ERROR in /Users/Milligan/Documents/Angular/MovieSeatReservation/node_modules/angularfire2/database/query_observable.d.ts (2,83): Cannot find module '../interfaces'.
ERROR in /Users/Milligan/Documents/Angular/MovieSeatReservation/node_modules/angularfire2/database/database.module.d.ts (2,10): Module '"/Users/Milligan/Documents/Angular/MovieSeatReservation/node_modules/angularfire2/angularfire2"' has no exported member 'FirebaseApp'.
ERROR in Error: Error encountered resolving symbol values statically. Could not resolve @angular/core relative to /Users/Milligan/node_modules/angularfire2/index.d.ts., resolving symbol FirebaseAppConfigToken in /Users/Milligan/node_modules/angularfire2/index.d.ts, resolving symbol FirebaseAppConfigToken in /Users/Milligan/node_modules/angularfire2/index.d.ts, resolving symbol AngularFireModule.initializeApp in /Users/Milligan/node_modules/angularfire2/index.d.ts, resolving symbol AppModule in /Users/Milligan/Documents/Angular/MovieSeatReservation/src/app/app.module.ts, resolving symbol AppModule in /Users/Milligan/Documents/Angular/MovieSeatReservation/src/app/app.module.ts
    at Error (native)
    at syntaxError (/Users/Milligan/Documents/Angular/MovieSeatReservation/node_modules/@angular/compiler/bundles/compiler.umd.js:1729:34)
    at simplifyInContext (/Users/Milligan/Documents/Angular/MovieSeatReservation/node_modules/@angular/compiler/bundles/compiler.umd.js:25118:23)
    at StaticReflector.simplify (/Users/Milligan/Documents/Angular/MovieSeatReservation/node_modules/@angular/compiler/bundles/compiler.umd.js:25130:13)
    at StaticReflector.annotations (/Users/Milligan/Documents/Angular/MovieSeatReservation/node_modules/@angular/compiler/bundles/compiler.umd.js:24558:41)
    at _getNgModuleMetadata (/Users/Milligan/Documents/Angular/MovieSeatReservation/node_modules/@angular/compiler-cli/src/ngtools_impl.js:138:31)
    at _extractLazyRoutesFromStaticModule (/Users/Milligan/Documents/Angular/MovieSeatReservation/node_modules/@angular/compiler-cli/src/ngtools_impl.js:109:26)
    at Object.listLazyRoutesOfModule (/Users/Milligan/Documents/Angular/MovieSeatReservation/node_modules/@angular/compiler-cli/src/ngtools_impl.js:53:22)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (/Users/Milligan/Documents/Angular/MovieSeatReservation/node_modules/@angular/compiler-cli/src/ngtools_api.js:91:39)
    at AotPlugin._getLazyRoutesFromNgtools (/Users/Milligan/Documents/Angular/MovieSeatReservation/node_modules/@ngtools/webpack/src/plugin.js:212:44)
    at _donePromise.Promise.resolve.then.then.then.then.then (/Users/Milligan/Documents/Angular/MovieSeatReservation/node_modules/@ngtools/webpack/src/plugin.js:448:24)
    at process._tickCallback (internal/process/next_tick.js:109:7)

webpack: Failed to compile.

I am running NPM v3.10.10 and Node v6.11.4. I have also upgrade AngularFire to 5.0

**Comment by NewtonJoshua** [comment]
The project was built using angularfire2 v4.0.
You can use it with v5.0 by following the [migration guide](https://github.com/angular/angularfire2/blob/master/docs/version-5-upgrade.md)
